# Generated by Django 4.0.1 on 2022-04-21 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicchem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqrtEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.FloatField(blank=True, null=True)),
                ('second_number', models.FloatField(blank=True, null=True)),
                ('third_number', models.FloatField(blank=True, null=True)),
                ('des_1', models.FloatField(blank=True, null=True)),
                ('des_2', models.FloatField(blank=True, null=True)),
                ('unpossible', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='basicchem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicchem',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basicchem.category'),
        ),
        migrations.AlterField(
            model_name='basicchem',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
